/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apk_inv;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.sql.SQLException;
import java.sql.*;
/**
 *
 * @author Agung
 */
public class dashboard extends javax.swing.JFrame {
//    private Object jDesktopPane1;

    /**
     * Creates new form dashboard
     */
    Apk_inv.koneksi koneksinya = new Apk_inv.koneksi();
    Apk_inv.SesiPemilik PemilikSession = new Apk_inv.SesiPemilik();
    Apk_inv.SesiAdmin AdminSession = new Apk_inv.SesiAdmin();
    public dashboard() {
        initComponents();
        set_nama();
        this.setLocationRelativeTo(null);
    }
    
    public void set_nama(){
        jlbl_username.setText(AdminSession.GetU_nama_user());
        jlbl_jenis_akses.setText(AdminSession.GetU_jenis_akses());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_barang = new javax.swing.JLabel();
        txt_supplier = new javax.swing.JLabel();
        logo_barang = new javax.swing.JLabel();
        logo_supplier = new javax.swing.JLabel();
        txt_karyawan = new javax.swing.JLabel();
        logo_karyawan = new javax.swing.JLabel();
        logo_logout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlbl_jenis_akses = new javax.swing.JLabel();
        jlbl_username = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_barang.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_barang.setText("Data Barang");
        getContentPane().add(txt_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 160, 50));

        txt_supplier.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_supplier.setText("Data Supplier");
        getContentPane().add(txt_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 170, 50));

        logo_barang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplikasi_inventory/images/barang.png"))); // NOI18N
        logo_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logo_barangMouseClicked(evt);
            }
        });
        getContentPane().add(logo_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 150, 140));

        logo_supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplikasi_inventory/images/logo_supplier.png"))); // NOI18N
        logo_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logo_supplierMouseClicked(evt);
            }
        });
        getContentPane().add(logo_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 150, 120));

        txt_karyawan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_karyawan.setText("Data Karyawan");
        txt_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_karyawanMouseClicked(evt);
            }
        });
        getContentPane().add(txt_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 230, 200, 50));

        logo_karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplikasi_inventory/images/add.png"))); // NOI18N
        logo_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logo_karyawanMouseClicked(evt);
            }
        });
        getContentPane().add(logo_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 140, 140));

        logo_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplikasi_inventory/images/exit.png"))); // NOI18N
        logo_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logo_logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logo_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 500, 130, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplikasi_inventory/images/man.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 130, 130));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("SISTEM PERSEDIAAN BARANG");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 570, 50));

        jlbl_jenis_akses.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbl_jenis_akses.setText("-");
        getContentPane().add(jlbl_jenis_akses, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 60, -1));

        jlbl_username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbl_username.setText("-");
        jlbl_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbl_usernameMouseClicked(evt);
            }
        });
        getContentPane().add(jlbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 70, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Welcome Admin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 160, 100));

        jLabel5.setText("Username");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jLabel6.setText("Jenis Akses");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 70, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplikasi_inventory/images/dashboard2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logo_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logo_barangMouseClicked
        new barang().setVisible(true);
        dispose();
    }//GEN-LAST:event_logo_barangMouseClicked

    private void logo_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logo_supplierMouseClicked
        new supplier().setVisible(true);
        dispose();
    }//GEN-LAST:event_logo_supplierMouseClicked

    private void logo_karyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logo_karyawanMouseClicked
        new detail_karyawan().setVisible(true);
        dispose();
    }//GEN-LAST:event_logo_karyawanMouseClicked

    private void logo_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logo_logoutMouseClicked
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_logo_logoutMouseClicked

    private void txt_karyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_karyawanMouseClicked

    }//GEN-LAST:event_txt_karyawanMouseClicked

    private void jlbl_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_usernameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbl_usernameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jlbl_jenis_akses;
    public javax.swing.JLabel jlbl_username;
    private javax.swing.JLabel logo_barang;
    private javax.swing.JLabel logo_karyawan;
    private javax.swing.JLabel logo_logout;
    private javax.swing.JLabel logo_supplier;
    private javax.swing.JLabel txt_barang;
    private javax.swing.JLabel txt_karyawan;
    private javax.swing.JLabel txt_supplier;
    // End of variables declaration//GEN-END:variables
}
