/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apk_inv;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.table.DefaultTableModel;
import session.session_login;
import java.sql.SQLException;
import java.sql.*;

/**
 *
 * @author Agung
 */
public class detail_karyawan extends javax.swing.JFrame {
    Connection conn = new db_koneksi().membukakoneksi();
    Statement stat;
    ResultSet res;
    DefaultTableModel tb;
    /**
     * Creates new form detail_karyawan
     */
    public detail_karyawan() {
        initComponents();
        showTable();
        this.setLocationRelativeTo(null);
    }
    
    public void showTable(){
        try {
            stat = conn.createStatement();
            tb = new DefaultTableModel();
            tb.addColumn("Id User");
            tb.addColumn("Username");
            tb.addColumn("Password");
            tb.addColumn("Hak Ases");
            tabel_detailkar.setModel(tb);
            
            String sql = "select * from user";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            while (res.next()) {                
                tb.addRow(new Object[]{
                res.getString("id_user"),
                res.getString("username"),
                res.getString("password"),
                res.getString("jenis_akses")});
            }
          
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Terjadi kesalahan" +e.getMessage());
        }
    }
    
    public void hapusData() {
        try {
            String sql = "DELETE FROM user WHERE id_user='"+jTextField2.getText()+"'";
            stat = conn.createStatement();
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "berhasil dihapus");
            showTable();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "terjadi kesalahan " + e.getMessage());
        }    
    }
        


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_detailkar = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jPasswordField1 = new javax.swing.JPasswordField();
        edit_barang = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_detailkar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_detailkar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_detailkarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_detailkar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 550, 250));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplikasi_inventory/images/delete.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 50, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplikasi_inventory/images/back.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 50, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Detail Karyawan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 70));

        jLabel5.setText("Jenis_Akses");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 80, 20));

        jLabel6.setText("Username");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 70, 20));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 140, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--PILIH--", "admin", "karyawan" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 140, 40));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 140, 40));

        edit_barang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplikasi_inventory/images/edit.png"))); // NOI18N
        edit_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_barangMouseClicked(evt);
            }
        });
        getContentPane().add(edit_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 40, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       hapusData();
       jTextField2.setText(" ");
       jPasswordField1.setText(" ");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        int id = session_login.getJenis_akses();
        if (id == 1) {
            new dashboard().setVisible(true);
            this.dispose();
            System.out.println("akses = "+id);
        }else if(id == 0){
            new dashboard2().setVisible(true);
            this.dispose();
            System.out.println("akses = "+id);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void edit_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_barangMouseClicked
//        editData();
//        kd_otomatis();
//        //txt_idbarang.setText(" ");
//        txt_namabarang.setText(" ");
//        txt_hargabeli.setText(" ");
//        txt_hargajual.setText(" ");
//        txt_stok.setText(" ");
    }//GEN-LAST:event_edit_barangMouseClicked

    private void tabel_detailkarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_detailkarMouseClicked
        int selectedRow=tabel_detailkar.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel)tabel_detailkar.getModel();
        jTextField2.setText(model.getValueAt(selectedRow, 0).toString());
        jPasswordField1.setText(model.getValueAt(selectedRow, 1).toString());
    }//GEN-LAST:event_tabel_detailkarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detail_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detail_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detail_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detail_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detail_karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel edit_barang;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tabel_detailkar;
    // End of variables declaration//GEN-END:variables
}
