/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apk_inv;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.*;
import java.sql.*;
/**
 *
 * @author Agung
 */
public class Laporan_1 extends javax.swing.JDialog {

    /**
     * Creates new form Laporan_1
     */
    Apk_inv.db_koneksi konek = new Apk_inv.db_koneksi();
    Apk_inv.report report = new Apk_inv.report();
    public Laporan_1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initUI();
        dateEnabled(false);
    }
    
    private void initUI(){ 
        getContentPane().setBackground(new Color(245, 245, 245));
        
        Dimension windowSize = getSize();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();
        int dx = centerPoint.x - windowSize.width / 2;
        int dy = centerPoint.y - windowSize.height / 2;    
        setLocation(dx, dy);
    }
     private void dateEnabled(boolean x){
        txtd_dari.setEnabled(x);
        txtd_sampai.setEnabled(x);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btncetak = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbid_laporan = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtd_dari = new com.toedter.calendar.JDateChooser();
        txtd_sampai = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplikasi_inventory/images/back.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 50, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Cetak Laporan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 110, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 70));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplikasi_inventory/images/Print.png"))); // NOI18N
        btncetak.setText("Cetak");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });
        jPanel2.add(btncetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 100, 30));

        jLabel3.setText("Laporan");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 50, 20));

        cmbid_laporan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih", "Stok Barang", "Barang Masuk", "Barang Keluar", "Return" }));
        cmbid_laporan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbid_laporanItemStateChanged(evt);
            }
        });
        jPanel2.add(cmbid_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 140, -1));

        jLabel4.setText("Sampai Tanggal");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 100, -1));

        txtd_dari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtd_dariMouseClicked(evt);
            }
        });
        jPanel2.add(txtd_dari, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 140, -1));
        jPanel2.add(txtd_sampai, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 140, -1));

        jLabel5.setText("Dari Tanggal");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 370, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
                String id_laporan = cmbid_laporan.getSelectedItem().toString();
                switch (id_laporan) {
                        case "Pilih":
                        JOptionPane.showMessageDialog(null, "Terdapat inputan yang kosong.");
                        break;
                        case "Stok Barang":
                        try {
                                File file = new File("src/Apk_inv/laporanstokbarang.jrxml");
                                JasperDesign jasperDesign = JRXmlLoader.load(file);
                                JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
                                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, db_koneksi.membukakoneksi());
                                JasperViewer.viewReport(jasperPrint, false);
                            }catch (JRException e) {
                                JOptionPane.showMessageDialog(null, "COBA SEKALI" + e);
                            }
                        this.hide();
                        break;
                        default:
                        SimpleDateFormat date;
                        date = new SimpleDateFormat("yyyy-MM-dd");
                        String d_dari = date.format(txtd_dari.getDate());
                        String d_sampai = date.format(txtd_sampai.getDate());
                        if(id_laporan.equals("Barang Masuk")){
                                try {
                                    HashMap hash = new HashMap();
                                    hash.put("d_dari",d_dari);
                                    hash.put("d_sampai", d_sampai);
                    
                                    File file1 = new File("src/Apk_inv/report_barangMasuk.jrxml");
                                    JasperDesign jasperDesign = JRXmlLoader.load(file1);
                                    JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
                                    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, hash, db_koneksi.membukakoneksi());
                                    JasperViewer.viewReport(jasperPrint, false);
                                    }catch (JRException e) {
                                        JOptionPane.showMessageDialog(null, "COBA SEKALI " + e);
                                    }
                            }else if(id_laporan.equals("Barang Keluar")){
                                try {
                                    HashMap hash = new HashMap();
                                    hash.put("d_dari", d_dari);
                                    hash.put("d_sampai", d_sampai);
                                    File file2 = new File("src/Apk_inv/report_barangKeluar.jrxml");
                                    JasperDesign jasperDesign = JRXmlLoader.load(file2);
                                    JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
                                    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, hash, db_koneksi.membukakoneksi());
                                    JasperViewer.viewReport(jasperPrint, false);
                                    }catch (JRException e) {
                                        JOptionPane.showMessageDialog(null, "Error " + e);
                                    }
                            }
                                else if (id_laporan.equals("Return")){
                                try {
                                        HashMap hash = new HashMap();
                                        hash.put("d_dari", d_dari);
                                        hash.put("d_sampai", d_sampai);
                                        File file3 = new File("src/Apk_inv/report_barangReturn.jrxml");
                                        JasperDesign jasperDesign = JRXmlLoader.load(file3);
                                        JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
                                        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, hash, db_koneksi.membukakoneksi());
                                        JasperViewer.viewReport(jasperPrint, false);
                            } catch (Exception e) {
                            }
                            }
                        this.hide();
                        break;
                    }
    }//GEN-LAST:event_btncetakActionPerformed

    private void cmbid_laporanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbid_laporanItemStateChanged
        String id_laporan = cmbid_laporan.getSelectedItem().toString();
        if(id_laporan.equals("Stok Barang") || id_laporan.equals("Pilih")){
            dateEnabled(false);
        }else{
            dateEnabled(true);
            txtd_dari.requestFocus();
        }
    }//GEN-LAST:event_cmbid_laporanItemStateChanged

    private void txtd_dariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtd_dariMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtd_dariMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
               new dashboard2().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Laporan_1 dialog = new Laporan_1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncetak;
    private javax.swing.JComboBox cmbid_laporan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser txtd_dari;
    private com.toedter.calendar.JDateChooser txtd_sampai;
    // End of variables declaration//GEN-END:variables
}
