/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apk_inv;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.*;

/**
 *
 * @author Agung
 */
public class laporan extends javax.swing.JFrame {

    /**
     * Creates new form laporan
     */
    public laporan() {
        initComponents();
//        super(parent, modal);
        initComponents();
        initUI();
        dateEnabled(false);
    }
    
    private void initUI(){ 
        getContentPane().setBackground(new Color(245, 245, 245));
        
        Dimension windowSize = getSize();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();
        int dx = centerPoint.x - windowSize.width / 2;
        int dy = centerPoint.y - windowSize.height / 2;    
        setLocation(dx, dy);
    }
    
    private void dateEnabled(boolean x){
        txtd_dari.setEnabled(x);
        txtd_sampai.setEnabled(x);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbid_laporan = new javax.swing.JComboBox();
        txtd_dari = new com.toedter.calendar.JDateChooser();
        txtd_sampai = new com.toedter.calendar.JDateChooser();
        btncetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cetak Laporan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 120, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplikasi_inventory/images/back.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 40, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 70));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Laporan");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, 20));

        jLabel2.setText("Dari Tanggal");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, 20));

        jLabel4.setText("Sampai Tanggal");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, 20));

        cmbid_laporan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih", "Stok Barang", "Barang Masuk", "Barang Keluar", "Return", " " }));
        cmbid_laporan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbid_laporanItemStateChanged(evt);
            }
        });
        jPanel2.add(cmbid_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 120, -1));
        jPanel2.add(txtd_dari, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 120, -1));
        jPanel2.add(txtd_sampai, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 120, -1));

        btncetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplikasi_inventory/images/Print.png"))); // NOI18N
        btncetak.setText("Cetak");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });
        jPanel2.add(btncetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 90, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 430, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbid_laporanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbid_laporanItemStateChanged
        String id_laporan = cmbid_laporan.getSelectedItem().toString();
        if(id_laporan.equals("Stok Barang") || id_laporan.equals("Pilih")){
            dateEnabled(false);
        }else{
            dateEnabled(true);
            txtd_dari.requestFocus();
        }
    }//GEN-LAST:event_cmbid_laporanItemStateChanged

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
//String id_laporan = cmbid_laporan.getSelectedItem().toString();
//        switch (id_laporan) {
//            case "Pilih":
//                JOptionPane.showMessageDialog(null, "Terdapat inputan yang kosong.");
//                break;
//            case "stok barang":
//                try {
//                    File file = new File("laporanstokbarang.jrxml");
//                    JasperDesign jasperDesign = JRXmlLoader.load(file);
//                    JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
//                    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, db_koneksi.membukakoneksi());
//                    JasperViewer.viewReport(jasperPrint, false);
//                }catch (ClassNotFoundException | JRException e) {
//                    JOptionPane.showMessageDialog(null, "Error " + e);
//                }
//                this.hide();
//                break;
//            default:
//                SimpleDateFormat date;
//                date = new SimpleDateFormat("yyyy-MM-dd");
//                String d_dari = date.format(txtd_dari.getDate());
//                String d_sampai = date.format(txtd_sampai.getDate());
//                if(id_laporan.equals("Barang Masuk")){
//                    try {
//                        HashMap hash = new HashMap();
//                        hash.put("d_dari", d_dari);
//                        hash.put("d_sampai", d_sampai);
//                        
//                        File file1 = new File("src/report/report_barangMasuk.jrxml");
//                        JasperDesign jasperDesign = JRXmlLoader.load(file1);
//                        JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
//                        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, hash, db_koneksi.membukakoneksi());
//                        JasperViewer.viewReport(jasperPrint, false);
//                    }catch (ClassNotFoundException | JRException e) {
//                        JOptionPane.showMessageDialog(null, "Error " + e);
//                    }
//                }else if(id_laporan.equals("Barang Keluar")){
//                    try {
//                        HashMap hash = new HashMap();
//                        hash.put("d_dari", d_dari);
//                        hash.put("d_sampai", d_sampai);
//                        
//                        File file2 = new File("src/report/report_barangKeluar.jrxml");
//                        JasperDesign jasperDesign = JRXmlLoader.load(file2);
//                        JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
//                        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, hash, db_koneksi.membukakoneksi());
//                        JasperViewer.viewReport(jasperPrint, false);
//                    }catch (ClassNotFoundException | JRException e) {
//                        JOptionPane.showMessageDialog(null, "Error " + e);
//                    }
//                }
//                this.hide();
//                break;
//        }
    }//GEN-LAST:event_btncetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncetak;
    private javax.swing.JComboBox cmbid_laporan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser txtd_dari;
    private com.toedter.calendar.JDateChooser txtd_sampai;
    // End of variables declaration//GEN-END:variables
}
